version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./data:/app/data
    ports:
      - 5280:5000
    env_file:
      - .env
    networks:
      - game-backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 4137:3000
    env_file:
      - .env
    networks:
      - game-backend

networks:
  game-backend:
    external: true
