# Start from a Python image
FROM python:3.8-slim-buster

# Set the working directory
WORKDIR /app

# Copy over the python files and requirements
COPY backend/ /app

# Install the python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install git
RUN apt-get update && apt-get install -y git

# Expose the port for the server
EXPOSE 5280

# Start the server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5280"]
