version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - 5280:5280
    env_file:
      - .env
    networks:
      - game-backend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: always
    ports:
      - 4137:4137
    env_file:
      - .env
    networks:
      - game-backend

networks:
  game-backend:
    external: true
